
import inspect, os
__INSTALL_DIR__ = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

__OUTDIR__ = config["outdir"]

###############################################################################

localrules: mappingBlastDB, mapping, output

  # Generate blast databases for each genome
rule mappingBlastDB:
  input:
    fa = lambda wildcards: config["genomes"][wildcards.genome]["fasta"]
  output:
    db = "%s/blastdb.{genome}.db"% __OUTDIR__
  params:
    dbtype = lambda wildcards: 'prot' if config["genomes"][wildcards.genome]["is_prot"] else "nucl"
  conda: "conda.yaml"
  shell: """
    makeblastdb -in "{input.fa}" -dbtype {params.dbtype} -out "{output.db}"
    touch "{output.db}"
  """

def determineBlastType(protA, protB):
  if protA and protB:
    return "blastp"
  if protA and (not protB):
    return "blastx"
  if (not protA) and protB:
    return "tblastn"
  if not (protA or protB):
    return "blastn"
  #fi
#edef

  # Blast genome_db vs genome_query and vice-versa
rule mappingBlastQuery:
  input:
    db    = lambda wildcards: "%s/blastdb.%s.db" % (__OUTDIR__, wildcards.genome_db),
    trans = lambda wildcards: config["genomes"][wildcards.genome_query]["fasta"]
  output:
    res = "%s/result.{genome_db}.{genome_query}.tsv"% __OUTDIR__
  conda: "conda.yaml"
  params:
    blast_fields = config["blast_fields"],
    blast_type   = lambda wildcards: determineBlastType(config["genomes"][wildcards.genome_db]["is_prot"], config["genomes"][wildcards.genome_query]["is_prot"]),
    evalue       = config["e_threshold"],
    options   = config["options"],
  threads: 5
  shell: """
    {params.blast_type} -num_threads "{threads}" -outfmt "6 {params.blast_fields}" {params.options} -evalue {params.evalue} -query "{input.trans}" -db "{input.db}" -out "{output.res}"
  """

  # Perform a reciprocal best blast hit to identify karyollele pairs
rule output:
  input:
    g1v2 = expand("%s/result.{genome_db}.{genome_query}.tsv" % __OUTDIR__, genome_db=["A"], genome_query=["B"]),
  output:
    res = "%s/%s" % (config["outdir"], config["output_file_name"])
  shell: """
    ln -s "{input.g1v2}" "{output.res}"
  """
