###############################################################################
# LIFTOVER PIPELINE                                                           #
###############################################################################

rule download_chain:
  output:
    chain = "%s/%s_%s.chain" % (config["common_dir"], config["fromAssembly"], config["toAssembly"])
  params:
    chainURL = config["chainURL"]
  shell: """
    curl -L "{params.chainURL}" | zcat > "{output.chain}"
  """

rule liftOver:
  input:
    data = config["input_file"],
    chain = rules.download_chain.output.chain
  output:
    res = "%s/lifted.bed" % config["outdir"],
    unmapped = "%s/unlifted.bed" % config["outdir"]
  conda: "conda.yaml"
  shell: """
    liftOver "{input.data}" "{input.chain}" "{output.res}" "{output.unmapped}"
  """

rule output:
  input:
    res = rules.liftOver.output.res
  output:
    res = "%s/%s" % (config["outdir"], config["output_file_name"])
  shell: """
    ln -s "{input.res}" "{output.res}"
  """
